### ISSUE TITLE
bodyLengthMismatch errors from S3 putObject with stream

### ISSUE THREAD

**Issue by rnikander** [soto-project/soto#432]
Using version 5 beta branch and `AWSPayload.stream`, the S3 `putObject` request fails with `HTTPClientError.bodyLengthMismatch` for certain files. Many files will upload fine, and then in will repeatedly fail for a certain file. It seems related to the size of the `ByteBuffer` that I return from the closure argument to `AWSPayload.stream`. But I can't see why it likes some sizes and not others. 

(In a previous version of this comment I said it was anything over a certain size, but I see now that is not the case.)

**Comment by rnikander** [comment]
Some demo code...

    let cpf: CredentialProviderFactory = .static(accessKeyId: "...",
                                                 secretAccessKey: "...")
    let awsClient = AWSClient(credentialProvider: cpf, httpClientProvider: .createNew)
    let s3 = S3(client: awsClient, region: .useast1)
    let okSize = 60000
    let errSize1 = 65537
    let errSize2 = 65552
    
    func tryIt(size: Int) -> Bool {
        let data = Data(count: size)
        print("Trying with data size \(size)")
        let bb = ByteBuffer(data: data)
        var sentBuffer = false
        let payload = AWSPayload.stream(size: bb.readableBytes) { eventLoop in // (stream: <#T##(EventLoop) -> EventLoopFuture<StreamReaderResult>#>)
            if sentBuffer {
                print("end") // not called
                return eventLoop.makeSucceededFuture(.end)
            }
            print("Sending buffer \(bb.readableBytes)")
            sentBuffer = true
            return eventLoop.makeSucceededFuture(StreamReaderResult.byteBuffer(bb))
        }
        let req = S3.PutObjectRequest(body: payload, bucket: "archives.encodia.co", key: "test-error")
        let fut = s3.putObject(req)
        do {
            try fut.wait()
        } catch {
            if let hce = error as? HTTPClientError, hce == .bodyLengthMismatch {
                print("body mismatch error")
                return false
            }
            if let are = error as? SotoCore.AWSResponseError, are.errorCode == "IncompleteBody" {
                print("incomplete body error")
                return false
            }
            print("Unexpected error \(error.localizedDescription)")
            fatalError()
        }
        print("It worked.")
        return true
    }
    
    tryIt(size: okSize)
    tryIt(size: errSize1)
    tryIt(size: errSize2)
    
    try! awsClient.syncShutdown()

Prints:

    Trying with data size 60000
    Sending buffer 60000
    It worked.

    Trying with data size 65537
    Sending buffer 65537
    incomplete body error

    Trying with data size 65552
    Sending buffer 65552
    body mismatch error

**Comment by adam-fowler** [comment]
Damn I verified this with multiple sizes. The S3 chunked upload is fairly complex as you need to sign each chunk so there was always a chance of something not working 100%. 

You mention in your code the streaming closure is not called the second time. That is because you have supplied a size (which S3 requires, not all services do). As soon as you have supplied the amount of data required it stops calling the streaming closure. You only need to return .end in the situation where a size isn't provided. 

I'll have a look into this

**Comment by adam-fowler** [comment]
Fixed. Issue with sending buffers to streamer in chunks larger than 64kb https://github.com/soto-project/soto-core/pull/400

**Comment by rnikander** [comment]
I'm not sure how to test this (what package versions/branches to put into Xcode) but as soon as I can test it I will.

**Comment by adam-fowler** [comment]
> I'm not sure how to test this (what package versions/branches to put into Xcode) but as soon as I can test it I will.

You should be able to use the main branch as I merged it this morning

**Comment by rnikander** [comment]
It seems better, like it went longer without error, but it threw the error again after uploading about a GB of files. I have a breakpoint at line 908 of async-http-client: HTTPHandler.swift (will attach screenshot).

**Comment by rnikander** [comment]
<img width="1129" alt="Screen Shot 2020-11-09 at 11 43 18 AM" src="https://user-images.githubusercontent.com/1702134/98569872-cd45e400-2280-11eb-9f6a-f43c0a94c5bc.png">

**Comment by adam-fowler** [comment]
This is with what size data, supplied in what size blocks?

**Comment by rnikander** [comment]
The blocks were 100,000 bytes, until the last one of course. The file was a few MB. I've killed the program but let me know if you'd like me to try to gather more info next time it happens. I also took a screenshot of the stacktrace displayed in Xcode, but with all the async I'm not sure it's worth much.

**Comment by adam-fowler** [comment]
Are you sure you aren't sending too much data?

**Comment by adam-fowler** [comment]
I've added some checks to see if an `AWSPayload.stream` function is supplying the correct amount of data. 
- If you provide too much data it will throw a `AWSClient.ClientError.tooMuchData` error. 
- If you don't provide enough data and send a `.end` it will throw a `AWSClient.ClientError.notEnoughData` error. 
If you update to the latest version of the main branch, you'll get these errors

**Comment by rnikander** [comment]
Okay. I'll be re-running things in the next hour or so, and I'll find out what's going on.

**Comment by adam-fowler** [comment]
Is this one resolved now?

**Comment by rnikander** [comment]
I thought I saw it again earlier, but it could be a bug in my code. I'm uploading tons of files so lots of testing. I'll close this in a few days if I don't see it again, if that's okay.

**Comment by rnikander** [comment]
I'm still getting this, rarely, but it's hard to reproduce. Re-running with same file won't do it, which suggests to me it could be a race condition somewhere on some shared state. It certainly could be something weird in my code, so I'm trying to reproduce it now on a simpler test program.

**Comment by adam-fowler** [comment]
Are you getting the `bodyLengthMismatch` error or the new errors I added `AWSClient.notEnoughData` and `AWSClient.tooMuchData`?
Also you have verified you are sending the correct amount of data?

**Comment by rnikander** [comment]
I'll double check next time but I thought it was bodyLengthMismatch. Maybe my swift packages are not updated properly. If it helps, I have a breakpoint that was triggered on ([line 908 of HttpHandler.swift in the package async-http-client](https://github.com/swift-server/async-http-client/blob/0a8dddbe15cd72f7bb5e47951fb7c1eb0836dfc2/Sources/AsyncHTTPClient/HTTPHandler.swift#L908)). 

I think I'm sending the right data, and 1000s of files upload without a problem, but my program is complicated so maybe there is a subtle bug somewhere.  That's why I'm trying to reproduce in a simpler test program.

**Comment by adam-fowler** [comment]
@rnikander have you any update on this?

**Comment by rnikander** [comment]
I'd say let's close it. On this project where I use Soto, I code in spurts. I haven't touched it in about 10 days. If I see this again, I'll try to make something reproducible and open another issue.
